-- Tambah 2 hirarki di atas MANAGER: REGIONAL MANAGER, GENERAL MANAGER.
-- Urutan rantai: SPG -> SUPERVISOR -> MANAGER -> REGIONAL MANAGER -> GENERAL MANAGER.
-- ADMINISTRATOR tetap terpisah, tidak dibatasi hirarki (UNRESTRICTED_ROLES).
ALTER TABLE users MODIFY COLUMN role ENUM(
    'SPG',
    'SUPERVISOR',
    'MANAGER',
    'REGIONAL MANAGER',
    'GENERAL MANAGER',
    'ADMINISTRATOR'
) DEFAULT 'SPG';
